#!/usr/bin/env python3
"""Generate references/rule-digests.md — the one-page rule facts file.

WHY THIS EXISTS
  The skill's rules live in rules/*.md, but no run step ever opened
  them (verified in review, 2026-09): rule text never entered the
  agent's context, so rules were written and then forgotten. The
  digest fixes that: a script-built summary of every rule (id, type,
  expect, on_fail) grouped by step. step_0 reads it once; each rule
  is then anchored in context at the moment it matters. The file is
  generated, never hand-edited: change the rule file, re-run this,
  hand edits are overwritten.

WHERE IT IS INVOKED
  - step_retro (SKILL.md, line 3): after a retro batch is activated,
    run this so the digest carries the new rules.
  - The scripts block in SKILL.md shows the one-liner.
  - Any time you suspect drift between rules/, the SKILL.md step
    lists, and the digest: it fails loudly on a step that lists a
    rule that does not exist, and warns on orphan rules and stale
    rule frontmatter.

USAGE
  python3 scripts/build_digests.py             # write references/rule-digests.md
  python3 scripts/build_digests.py --stdout    # preview without writing

  exit 0 = written (or printed) / 1 = drift found, fix first /
  2 = usage error"""

import argparse
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rules_meta as rm

OUT = rm.SKILL_ROOT / "references" / "rule-digests.md"


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Build references/rule-digests.md from the rule corpus."
    )
    ap.add_argument("--stdout", action="store_true",
                    help="print the digest instead of writing the file")
    a = ap.parse_args()

    rules, steps = rm.load_rules(), rm.load_steps()
    problems, warnings = [], []

    listed = set()
    for s in steps:
        for r in s["rules"]:
            if r not in rules:
                problems.append(
                    f"step {s['id']} lists rule '{rm.display(r)}' "
                    f"but rules/{rm.display(r)}.md does not exist")
            listed.add(r)
    for key in sorted(set(rules) - listed):
        warnings.append(
            f"rule {rm.display(key)} exists but no step lists it "
            f"(orphan — wire it into a SKILL.md step rules list or retire it)")
    for key, meta in sorted(rules.items()):
        for step in meta["applies_to"]:
            known = {s["id"] for s in steps} | set(rm.STEP_ARTIFACTS)
            if step.startswith("step_") and step not in known:
                warnings.append(
                    f"rule {rm.display(key)} applies_to '{step}' "
                    f"matches no SKILL.md step (stale frontmatter?)")
        if not meta["expect"]:
            problems.append(f"rule {rm.display(key)} has no expect "
                            f"(frontmatter `expect:` or a `## Rule` section)")
        if not meta["on_fail"]:
            warnings.append(f"rule {rm.display(key)} has no on_fail action")
        if meta["type"] not in (rm.CONTENT_TYPES | rm.PROCESS_TYPES):
            problems.append(f"rule {rm.display(key)} type "
                            f"{meta['type']!r} is neither a content nor a "
                            f"process type (edit its frontmatter)")

    lines = [
        "<!-- generated by scripts/build_digests.py — do not hand-edit; "
        "regenerate after any retro batch -->",
        "",
        f"# Rule digests ({len(rules)} rules, {len(steps)} steps, "
        f"built {date.today().isoformat()})",
        "",
        "One row per rule per step, straight from the frontmatter of",
        "`rules/*.md` (expect falls back to the rule's own ## Rule prose).",
        "Read once at step_0 alongside operating-principles.md, and cite",
        "rule ids at checkpoints. Every step closes its per-rule check",
        "loop (scripts/check_rules.py) before the checkpoint: each rule",
        "gets one check file in its own attention window. The `check`",
        "column says what the gate demands in that file: `quote` = a span",
        "copied verbatim from the step's artifact; `confirm` = a written",
        "statement of how the rule is honored (process rules cannot be",
        "quoted from the artifact).",
        "",
    ]
    for s in steps:
        loop = rm.loop_rules(s["id"], rules, steps)
        artifact = rm.STEP_ARTIFACTS.get(s["id"], "")
        lines.append(f"## {s['id']}"
                      + (f" — checked against `{artifact}`" if artifact else ""))
        lines.append("")
        if loop:
            lines.append("| rule | type | check | expect | on_fail |")
            lines.append("|---|---|---|---|---|")
            for meta in loop:
                check = ("quote" if rm.needs_quote(meta, s["id"])
                         else "confirm")
                lines.append(
                    f"| {rm.display(meta['id'])} | {meta['type']} | {check} "
                    f"| {meta['expect']} | {meta['on_fail'] or '—'} |")
        else:
            lines.append("_(no rules listed)_")
        lines.append("")

    text = "\n".join(lines) + "\n"
    for w in warnings:
        print(f"warn: {w}", file=sys.stderr)
    if problems:
        for p in problems:
            print(f"FAIL: {p}", file=sys.stderr)
        print("  fix: resolve the drift above, then re-run build_digests.py",
              file=sys.stderr)
        sys.exit(1)
    if a.stdout:
        print(text, end="")
    else:
        OUT.write_text(text)
        print(f"ok: wrote {OUT.relative_to(rm.SKILL_ROOT)} "
              f"({len(text.splitlines())} lines, {len(rules)} rules)")
        if warnings:
            print(f"note: {len(warnings)} warning(s) above do not block the "
                  f"build; clear them when convenient")


if __name__ == "__main__":
    main()