#!/usr/bin/env python3
"""Generate references/rule-digests.md: the one-page rule facts file.

WHY THIS EXISTS
  The skill's rules live in rules/*.md, but no run step ever opened
  them (verified in review, 2026-09): rule text never entered the
  agent's context, so rules were written and then forgotten. The
  digest fixes that: a script-built summary of every rule (id, type,
  expect, on_fail) grouped by step. step_0 reads it once; each rule
  is then anchored in context at the moment it matters. The file is
  generated, never hand-edited: change the rule file, re-run this,
  hand edits are overwritten.

WHERE IT IS INVOKED
  - step_retro (SKILL.md, line 3): after a retro batch is activated,
    run this so the digest carries the new rules.
  - The scripts block in SKILL.md shows the one-liner.
  - Any time you suspect drift between rules/, the SKILL.md step
    lists, and the digest: it fails loudly on a step that lists a
    rule that does not exist, on a rule with a missing or unknown
    `evidence:` field, on a quote/measure rule wired at a step with
    no artifact to quote or measure, and on a rule whose `applies_to`
    disagrees with its SKILL.md wiring; it warns on orphan rules and
    on rules missing an on_fail action.

USAGE
  python3 scripts/build_digests.py             # write references/rule-digests.md
  python3 scripts/build_digests.py --stdout    # preview without writing

  exit 0 = written (or printed) / 1 = drift found, fix first /
  2 = usage error"""

import argparse
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rules_meta as rm

OUT = rm.SKILL_ROOT / "references" / "rule-digests.md"


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Build references/rule-digests.md from the rule corpus."
    )
    ap.add_argument("--stdout", action="store_true",
                    help="print the digest instead of writing the file")
    a = ap.parse_args()

    rules, steps = rm.load_rules(), rm.load_steps()
    # proposed rules exist in rules/ but are not wired anywhere until the
    # retro activates them (user approval): keep them out of the digest,
    # the drift checks and the orphan warnings; report their existence.
    proposed = {k: m for k, m in rules.items()
                if m.get("status", "active") != "active"}
    rules = {k: m for k, m in rules.items()
             if m.get("status", "active") == "active"}
    problems, warnings = [], []

    listed = set()
    for s in steps:
        for r in s["rules"]:
            if r not in rules:
                problems.append(
                    f"step {s['id']} lists rule '{rm.display(r)}' "
                    f"but rules/{rm.display(r)}.md does not exist")
            listed.add(r)
    wired: dict[str, set[str]] = {}
    for s in steps:
        for r in s["rules"]:
            wired.setdefault(r, set()).add(s["id"])
    for key in sorted(set(rules) - listed):
        warnings.append(
            f"rule {rm.display(key)} exists but no step lists it "
            f"(orphan: wire it into a SKILL.md step rules list or retire it)")
    for key, meta in sorted(rules.items()):
        if not meta["expect"]:
            problems.append(f"rule {rm.display(key)} has no expect "
                            f"(frontmatter `expect:` or a `## Rule` section)")
        if not meta["on_fail"]:
            warnings.append(f"rule {rm.display(key)} has no on_fail action")
        if meta["type"] not in (rm.CONTENT_TYPES | rm.PROCESS_TYPES):
            problems.append(f"rule {rm.display(key)} type "
                            f"{meta['type']!r} is neither a content nor a "
                            f"process type (edit its frontmatter)")
        if not meta.get("evidence_raw"):
            problems.append(f"rule {rm.display(key)} has no `evidence:` "
                            "field: declare quote, confirm or measure "
                            "(the gate's demand is explicit per rule)")
        elif meta["evidence_raw"] not in rm.EVIDENCE_KINDS:
            problems.append(f"rule {rm.display(key)} evidence "
                            f"{meta['evidence_raw']!r} not in "
                            f"{list(rm.EVIDENCE_KINDS)}")
        ap = set(meta["applies_to"])
        w = wired.get(key, set())
        if "all" in ap:
            if w != {s["id"] for s in steps}:
                problems.append(f"rule {rm.display(key)} declares "
                                "applies_to [all] but SKILL.md wires it "
                                f"at {sorted(w)}")
        elif ap != w:
            problems.append(f"rule {rm.display(key)}: applies_to "
                            f"{sorted(ap)} and SKILL.md wiring {sorted(w)} "
                            "disagree: fix both to match")

    lines = [
        "<!-- generated by scripts/build_digests.py. Do not hand-edit; "
        "regenerate after any retro batch -->",
        "",
        f"# Rule digests ({len(rules)} rules, {len(steps)} steps, "
        f"built {date.today().isoformat()})",
        "",
        "One row per rule per step, straight from the frontmatter of",
        "`rules/*.md` (expect falls back to the rule's own ## Rule prose).",
        "Read once at step_0 alongside operating-principles.md, and cite",
        "rule ids at checkpoints. Every step closes its per-rule check",
        "loop (scripts/check_rules.py) before the checkpoint: each rule",
        "gets one check file in its own attention window. The `check`",
        "column says what the gate demands in that file: `quote` = a span",
        "copied verbatim from the step's artifact; `confirm` = a written",
        "statement of how the rule is honored; `measure` = the",
        "measurement stated in the note field, with its number (budget",
        "and size rules).",
        "",
    ]
    for s in steps:
        loop = rm.loop_rules(s["id"], rules, steps)
        artifact = rm.STEP_ARTIFACTS.get(s["id"], "")
        for meta in loop:
            if (meta["evidence"] in ("quote", "measure")
                    and not artifact):
                problems.append(
                    f"step {s['id']} wires {rm.display(meta['id'])} "
                    f"(evidence {meta['evidence']!r}) but has no artifact "
                    "to quote or measure. Rewire the rule or change "
                    "its evidence kind")
        lines.append(f"## {s['id']}"
                      + (f": checked against `{artifact}`" if artifact else ""))
        lines.append("")
        if loop:
            lines.append("| rule | type | check | expect | on_fail |")
            lines.append("|---|---|---|---|---|")
            for meta in loop:
                check = rm.evidence_kind(meta, s["id"])
                lines.append(
                    f"| {rm.display(meta['id'])} | {meta['type']} | {check} "
                    f"| {meta['expect']} | {meta['on_fail'] or '—'} |")
        else:
            lines.append("_(no rules listed)_")
        lines.append("")

    text = "\n".join(lines) + "\n"
    for w in warnings:
        print(f"warn: {w}", file=sys.stderr)
    if problems:
        for p in problems:
            print(f"FAIL: {p}", file=sys.stderr)
        print("  fix: resolve the drift above, then re-run build_digests.py",
              file=sys.stderr)
        sys.exit(1)
    if a.stdout:
        print(text, end="")
    else:
        if OUT.is_file():
            old = OUT.read_text().splitlines()
            # a rebuild must not show a diff when only the built date
            # moved: compare everything except the header line (the
            # rule and step counts always move with the tables)
            if [ln for ln in old
                    if not ln.startswith("# Rule digests (")] == \
               [ln for ln in lines
                    if not ln.startswith("# Rule digests (")]:
                print(f"ok: digest unchanged (content identical, "
                      f"{len(rules)} rules; not rewritten)")
                return
        OUT.write_text(text)
        print(f"ok: wrote {OUT.relative_to(rm.SKILL_ROOT)} "
              f"({len(text.splitlines())} lines, {len(rules)} rules)")
        if warnings:
            print(f"note: {len(warnings)} warning(s) above do not block the "
                  f"build; clear them when convenient")
        if proposed:
            print(f"note: {len(proposed)} proposed rule(s) not shown "
                  f"(awaiting retro approval): "
                  + ", ".join(rm.display(k) for k in sorted(proposed)))


if __name__ == "__main__":
    main()